In [2]:
import pandas as pd
import numpy as np

CCTV_Seoul = pd.read_csv('../data/01. CCTV_in_Seoul.csv')
CCTV_Seoul.rename(columns={CCTV_Seoul.columns[0] : '구별'}, inplace=True)
# 1. CCTV의 갯수로 정렬하기
a = CCTV_Seoul.sort_values(by='소계', ascending=True)

# 2. CCTV의 증가율 확인해보기
CCTV_Seoul['증가율'] = (CCTV_Seoul['2014년'] + CCTV_Seoul['2015년'] 
+ CCTV_Seoul['2016년']) / CCTV_Seoul['2013년도 이전'] * 100
b = CCTV_Seoul.sort_values(by='증가율', ascending=False)

# 3. 엑셀파일로 인구 수 받아오기
pop_Seoul = pd.read_excel('../data/01. population_in_Seoul.xls', header=2, usecols='B, D, G, J, N')
pop_Seoul.rename(columns={pop_Seoul.columns[0] : '구별', pop_Seoul.columns[1] : '인구수', pop_Seoul.columns[2] : '한국인', 
pop_Seoul.columns[3] : '외국인', pop_Seoul.columns[4] : '고령자'}, inplace=True)

# 4. 필요없는 행(합계) 삭제하기
pop_Seoul.drop([0], inplace=True)

# 5. 반복되는 행 조사하는 방법
pop_Seoul['구별'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', nan],
      dtype=object)

In [3]:
c = pop_Seoul[pop_Seoul['구별'].isnull()]
pop_Seoul.drop(c.index, inplace=True)
pop_Seoul['외국인비율'] = pop_Seoul['외국인']/pop_Seoul['인구수']*100
pop_Seoul['고령자비율'] = pop_Seoul['고령자']/pop_Seoul['인구수']*100

In [3]:
pop_Seoul

      구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
4    성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
5    광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849
6   동대문구  369496.0  354079.0  15417.0  54173.0  4.172440  14.661322
7    중랑구  414503.0  409882.0   4621.0  56774.0  1.114829  13.696885
8    성북구  461260.0  449773.0  11487.0  64692.0  2.490353  14.025062
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806  16.600342
10   도봉구  348646.0  346629.0   2017.0  51312.0  0.578524  14.717507
11   노원구  569384.0  565565.0   3819.0  71941.0  0.670725  12.634883
12   은평구  494388.0  489943.0   4445.0  72334.0  0.899091  14.631019
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221  14.720797
14   마포구  389649.0  378566.0  11083.0  48765.0  2.844355  12.515110
15   양천구  479978.0  475949.0   4029.0  52975.0  0.839413  11.036964
16   강서구  603772.0  597248.0   6524.0  72548.0  1.080540  12.015794
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998  12.689506
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598  13.006191
20   동작구  412520.0  400456.0  12064.0  56013.0  2.924464  13.578251
21   관악구  525515.0  507203.0  18312.0  68082.0  3.484582  12.955291
22   서초구  450310.0  445994.0   4316.0  51733.0  0.958451  11.488308
23   강남구  570500.0  565550.0   4950.0  63167.0  0.867660  11.072217
24   송파구  667483.0  660584.0   6899.0  72506.0  1.033584  10.862599
25   강동구  453233.0  449019.0   4214.0  54622.0  0.929765  12.051638

In [4]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7